version: '3'
services:
  wordpress:
    build: ./
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
      WORDPRESS_ADMIN_USERNAME: ${WORDPRESS_ADMIN_USERNAME}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      # Change Site URL to your local dev machine ip to fix redirection issues
      SITE_URL: ${SITE_URL}
      DEV_URL: ${DEV_URL}
      #Set to true to wipe out and reset your wordpress install (on next container rebuild)
      WP_RESET: ${WP_RESET}
    links:
      - db
    volumes:
      #Swap the folder path for plugin vs theme development
      - wordpress:/var/www/html
      - ../:/var/www/html/wp-content/plugins/plugin-dev
      #- ../:/var/www/html/wp-content/themes/theme-dev

  db:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  wordpress:
  data: